### ISSUE TITLE
Remove octokit deprecation notice.

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/bestbets-loader#12]
{ Deprecation: [@octokit/rest] octokit.authenticate() is deprecated. Use "auth" constructor option instead.
    at authenticate (/data/loader/bestbets-loader/v1/node_modules/@octokit/rest/plugins/authentication-deprecated/authenticate.js:9:44)
    at Function.GetInstance (/data/loader/bestbets-loader/v1/lib/sources/github-bestbets-source.js:370:14)
    at PipelineProcessor.loadPipelineStep (/data/loader/bestbets-loader/v1/node_modules/loader-pipeline/lib/pipeline-processor.js:171:49)
    at stepsToLoad.push (/data/loader/bestbets-loader/v1/node_modules/loader-pipeline/lib/pipeline-processor.js:193:42)
    at PipelineProcessor.loadPipeline (/data/loader/bestbets-loader/v1/node_modules/loader-pipeline/lib/pipeline-processor.js:194:11)
    at PipelineProcessor.run (/data/loader/bestbets-loader/v1/node_modules/loader-pipeline/lib/pipeline-processor.js:249:20)
    at main (/data/loader/bestbets-loader/v1/index.js:34:25)
    at Object.<anonymous> (/data/loader/bestbets-loader/v1/index.js:45:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10) name: 'Deprecation' }

**Comment by blairl-nih** [comment]
Addressed as part of #19
